[application]
name = "alarmfree"
default_platform = "android"
asset_dir = "assets"

[application.android]
min_sdk_version = 26
target_sdk_version = 34

[android]
min_sdk = 26
target_sdk = 34

[bundle]
identifier = "com.fidderr.alarmfree"
